version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.11.0-browsers
    steps:
      - checkout:
          path: ~/app
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm modules
          command: | 
            if [[ ! -d node_modules ]]; then
              npm ci
            fi
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules
      - run:
          name: Make a build
          command: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:10.11.0-browsers
    working_directory: ~/app
    steps:
      - checkout:
          path: ~/app
      - attach_workspace:
          at: ~/app
      - add_ssh_keys:
          fingerprints:
            - bf:f0:c3:6f:43:4c:6e:0b:29:ed:ab:93:c9:e9:33:85
      - run:
          name: "Setup Git"
          command: |
            git config --global user.email "moxon6@googlemail.com"
            git config --global user.name "Martin Moxon"
      - run:
          name: Deploy to gh-pages
          command: npm install gh-pages && npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master